In [ ]:
"""

University of Information Technology and Sciences (UITS)
          Name      : Md. Rifat Hassan
          ID        : 0432310005101064
          Semester  : Spring-2026
          Batch     : 53
          Section   : 7B1
          Department: CSE


          Course Code : CSE 413
          Course Title: Simulation and Modeling Lab

"""

In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
"""
Task 1 : Create Your Personal Matrix
Let:
    ● d1 = last digit of your student ID
    ● d2 = second last digit of your student ID

    Create the matrix:
    A = ([[d1 + 2, d2 + 1], [2 * d1, d2 + 2]])

"""

#ID: 64

d1 = 4
d2 = 6

A = np.array([[d1 + 2, d2 + 1], [2 * d1, d2 + 2]])
print(A)

[[6 7]
 [8 8]]


In [27]:
"""
Task 2: Analyze Matrix A

Using NumPy, compute:
    ● Shape of A
    ● Determinant
    ● Rank
    ● Eigenvalues
    ● Inverse (only if determinant ≠ 0)

"""

# Shape
shape_A = A.shape

# Determinant
det_A = np.linalg.det(A)

# Rank
rank_A = np.linalg.matrix_rank(A)

# Eigenvalues
eig_A = np.linalg.eigvals(A)

# Inverse (only if determinant ≠ 0)
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Impossible"

print("Shape       :", shape_A)
print("Determinant :", det_A)
print("Rank        :", rank_A)
print("Eigenvalues :", eig_A)
print("Inverse     :\n", inv_A)


Shape       : (2, 2)
Determinant : -7.999999999999998
Rank        : 2
Eigenvalues : [-0.54983444 14.54983444]
Inverse     :
 [[-1.     0.875]
 [ 1.    -0.75 ]]


In [28]:
"""
Task 3: Value Change Experiment

Create a new matrix B by changing exactly one value in A:
    ● Add +1 to one element of your choice
    ● You must clearly state which element you changed

"""

A = np.array([[d1 + 2, d2 + 1], [2 * d1, d2 + 2]])   # 1st element = d1 + 2
B = np.array([[d1 + 6, d2 + 1], [2 * d1, d2 + 2]])   # Change this element d1 + 2 = d1 + 6

print("Befor change Matrix A shown :\n",A)
print("\n After change Matrix B look like :\n",B)

Befor change Matrix A shown :
 [[6 7]
 [8 8]]

 After change Matrix B look like :
 [[10  7]
 [ 8  8]]


In [29]:
"""
Task 4: Re-analyze Matrix B

Compute the same properties as in Step 2.

"""

# Shape
shape_B = B.shape

# Determinant
det_B = np.linalg.det(B)

# Rank
rank_B = np.linalg.matrix_rank(B)

# Eigenvalues
eig_B = np.linalg.eigvals(B)

# Inverse (only if determinant ≠ 0)
if np.linalg.det(B) != 0:
    inv_B = np.linalg.inv(B)
else:
    inv_B = "Impossible"

print("Shape       :", shape_B)
print("Determinant :", det_B)
print("Rank        :", rank_B)
print("Eigenvalues :", eig_B)
print("Inverse     :\n", inv_B)

Shape       : (2, 2)
Determinant : 24.000000000000004
Rank        : 2
Eigenvalues : [16.54983444  1.45016556]
Inverse     :
 [[ 0.33333333 -0.29166667]
 [-0.33333333  0.41666667]]


In [ ]:
"""
Task 5: Comparison & Explanation

Answer the following in your own words:
    1. How did the determinant change and why?
    2. Did the rank change? Explain.
    3. How did the eigenvalues respond to the value change?
    4. Is B easier or harder to invert than A? Why?


Answer:
-------
1. How did the determinant change and why?
Ans:
The determinant increased because we changed the top‑left element of the matrix.
Since the determinant formula depends on the diagonal product minus the off‑diagonal product,
making that entry larger raised the diagonal product and therefore increased the determinant.

2. Did the rank change? Explain.
Ans:
No, the rank did not change. Both matrices still have two independent rows, so the rank remains 2.
Changing one element did not make the rows dependent on each other.

3. How did the eigenvalues respond to the value change?
Ans:
The eigenvalues shifted to different values. Eigenvalues are sensitive to changes in matrix entries,
so even a small modification in one element affects them.

4. Is B easier or harder to invert than A? Why?
Ans:
Both A and B are invertible because their determinants are non‑zero. However, B has a larger determinant,
which makes its inverse more stable. So B is slightly easier to invert compared to A.

"""